baseurl: /jekyll-course-experiment
markdown: redcarpet
permalink: /:categories/:title/
disqus_shortname: p2pugithub
exclude: [Gemfile, Gemfile.lock, README.md]
prose:
  media: img/
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css
