baseurl:
markdown: redcarpet
permalink: /:categories/:title/
ga_tracking_code: UA-5757664-19
exclude: [Gemfile, Gemfile.lock, README.md]
defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"
prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css
